name: Release

on:
    push:
        branches: [main]

jobs:
    release:
        - uses: actions/checkout@v2
          with:
              fetch-depth: 0
        - uses: actions/setup-node@v2
          with:
              node-version: 'lts/*'
        - name: Install Deps
          run: yarn
        - name: Run Tests
          run: yarn test
        - name: Build
          run: yarn build
        - name: Release
          env:
              GITHUB_TOKEN: ${{ secrets.GH_PAT }}
              NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          run: npx semantic-release
